In [2]:
import pandas as pd
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [3]:
file_path = open(file='../data/raw/dataset_2.csv')
df = pd.read_csv(file_path)
file_path.close()

df.head()
df.describe()

,Area_SqFt,Rooms,Build_Year,Location,Street_Type,Furnishing,Property_Type,Has_Pool,Price
0,2473.192784,4.0,1992,Jaipur,Residential Lane,Furnished,Apartment,No,568486.0
1,2353.472711,4.0,2006,Indore,Corner Plot,Unfurnished,Apartment,Yes,577214.0
2,2212.222005,3.0,2012,Jaipur,Highway Facing,Semi-Furnished,Duplex,No,581300.0
3,2823.886596,6.0,1993,Lucknow,Main Road,Unfurnished,Villa,Yes,794614.0
4,1869.648721,5.0,2012,Jaipur,Corner Plot,Semi-Furnished,Apartment,No,493086.0

          Area_SqFt        Rooms   Build_Year         Price
count   1091.000000  1091.000000  1124.000000  1.124000e+03
mean    2237.479473     4.568286  2005.080071  6.082015e+05
std      731.097828     1.678155    11.708876  1.431958e+05
min      700.000000     2.000000  1985.000000  2.486400e+05
25%     1834.022964     3.000000  1995.000000  5.161948e+05
50%     2201.545784     5.000000  2005.000000  6.025410e+05
75%     2576.139355     6.000000  2015.000000  6.895785e+05
max    10267.124330     7.000000  2024.000000  2.071402e+06

In [ ]:
import csv
from dataclasses import dataclass

@dataclass
class Model:
    area_sqft: str
    rooms: float
    build_year: int
    location: str
    street_type: str
    furnishing: str
    property_type: str
    has_pool: bool
    price: float


data_model = []

with open('../data/raw/dataset_2.csv', mode='r') as f:
    reader = csv.DictReader(f)

    for row in reader:
        obj = Model(area_sqft=row['Area_SqFt'],
                    rooms=row['Rooms'],
                    build_year=row['Build_Year'],
                    location=row['Location'],
                    street_type=row['Street_Type'],
                    furnishing=row['Furnishing'],
                    property_type=row['Property_Type'],
                    has_pool=row['Has_Pool'],
                    price=row['Price'])
        data_model.append(obj)


    data_model

Model(area_sqft='2415.16513', rooms='5', build_year='2011', location='Delhi', street_type='Main Road', furnishing='Semi-Furnished', property_type='Apartment', has_pool='Yes', price='720602')